# Generated by Django 4.2.7 on 2023-11-05 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_test', '0002_alter_answer_options_alter_answerscore_options_and_more'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectToPsychoTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('psycho_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_test.psychotest', verbose_name='Психологический тест')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Объект тестирования')),
            ],
            options={
                'verbose_name': 'Связь объекта тестирования с тестом',
                'verbose_name_plural': 'Связь объекта тестирования с тестом',
            },
        ),
    ]
