# Generated by Django 4.2.7 on 2023-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subjectidentity_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttopsychotest',
            name='token',
            field=models.CharField(default='', max_length=80, verbose_name='Токен доступа'),
            preserve_default=False,
        ),
    ]
