# Generated by Django 4.2.7 on 2023-11-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_subjecttopsychotestanswer_delete_subjecttoanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttopsychotestanswer',
            name='subject_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjecttopsychotest', verbose_name='Объект тестирования'),
        ),
    ]
