# Generated by Django 4.2.7 on 2023-11-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_subject_parent_alter_subject_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectidentity',
            name='secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectidentity',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
