# Generated by Django 4.2.7 on 2023-11-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['title'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answerscore',
            options={'ordering': ['created_at'], 'verbose_name': 'Ответ: Баллы', 'verbose_name_plural': 'Ответы: Баллы'},
        ),
        migrations.AlterModelOptions(
            name='answerscoreaction',
            options={'ordering': ['name'], 'verbose_name': 'Ответ: Действия с баллами', 'verbose_name_plural': 'Ответы: Действия с баллами'},
        ),
        migrations.AlterModelOptions(
            name='psychotest',
            options={'ordering': ['name'], 'verbose_name': 'Психологический тест', 'verbose_name_plural': 'Психологические тесты'},
        ),
        migrations.AlterModelOptions(
            name='psychotestquestiontoanswer',
            options={'ordering': ['created_at'], 'verbose_name': 'Психологический тест: Связь теста с ответом', 'verbose_name_plural': 'Психологические тесты: Связь теста с ответами'},
        ),
        migrations.AlterModelOptions(
            name='psychotestresultdictionary',
            options={'ordering': ['name'], 'verbose_name': 'Результат тестирования: Справочник', 'verbose_name_plural': 'Результаты тестирования: Справочник'},
        ),
        migrations.AlterModelOptions(
            name='psychotesttoquestion',
            options={'ordering': ['created_at'], 'verbose_name': 'Психологический тест: Связь тестирования с вопросом', 'verbose_name_plural': 'Психологические тесты: Связь тестирования с вопросом'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['title'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['name'], 'verbose_name': 'Вопрос: Тип', 'verbose_name_plural': 'Вопросы: Типы'},
        ),
    ]
