# Generated by Django 4.2.7 on 2023-11-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_test', '0004_alter_answer_created_at_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotest',
            name='answers',
            field=models.ManyToManyField(to='psycho_test.answer'),
        ),
    ]
